In [1]:
!pip install python-binance

Collecting python-binance
  Downloading python_binance-1.0.16-py2.py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.2/65.2 kB 1.7 MB/s eta 0:00:00
Collecting dateparser
  Downloading dateparser-1.1.1-py2.py3-none-any.whl (288 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.9/288.9 kB 6.2 MB/s eta 0:00:0000:01
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.9/site-packages (from python-binance) (3.8.1)
Collecting ujson
  Downloading ujson-5.4.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: websockets in /opt/conda/lib/python3.9/site-packages (from python-binance) (10.3)
Requirement already satisfied: six in /opt/conda/lib/python3.9/site-packages (from python-binance) (1.16.0)
Requirement already satisfied: requests in /opt/conda/lib/python3.9/site-packages (from python-binance) (2.26.0)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.9/site-packages (from aiohttp->python-binance) (1.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /opt/conda/lib/python3.9/site-packages (from aiohttp->python-binance) (4.0.2)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.9/site-packages (from aiohttp->python-binance) (6.0.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /opt/conda/lib/python3.9/site-packages (from aiohttp->python-binance) (2.0.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.9/site-packages (from aiohttp->python-binance) (1.8.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.9/site-packages (from aiohttp->python-binance) (19.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.9/site-packages (from aiohttp->python-binance) (1.3.1)
Requirement already satisfied: python-dateutil in /opt/conda/lib/python3.9/site-packages (from dateparser->python-binance) (2.8.0)
Collecting regex!=2019.02.19,!=2021.8.27,<2022.3.15
  Downloading regex-2022.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (763 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 763.5/763.5 kB 19.2 MB/s eta 0:00:0000:01
Collecting tzlocal
  Downloading tzlocal-4.2-py3-none-any.whl (19 kB)
Requirement already satisfied: pytz in /opt/conda/lib/python3.9/site-packages (from dateparser->python-binance) (2021.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.9/site-packages (from requests->python-binance) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.9/site-packages (from requests->python-binance) (3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.9/site-packages (from requests->python-binance) (1.26.7)
Collecting pytz-deprecation-shim
  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting tzdata
  Downloading tzdata-2022.2-py2.py3-none-any.whl (336 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 336.4/336.4 kB 12.2 MB/s eta 0:00:00
Installing collected packages: ujson, tzdata, regex, pytz-deprecation-shim, tzlocal, dateparser, python-binance
  Attempting uninstall: regex
    Found existing installation: regex 2022.8.17
    Uninstalling regex-2022.8.17:
      Successfully uninstalled regex-2022.8.17
Successfully installed dateparser-1.1.1 python-binance-1.0.16 pytz-deprecation-shim-0.1.0.post0 regex-2022.3.2 tzdata-2022.2 tzlocal-4.2 ujson-5.4.0

In [2]:
from binance import Client

In [4]:
import pandas as pd

In [6]:
api_key = "apikey"
api_secret = "apisecret" #api key and secret key from binance to authorize trading

In [7]:
client = Client(api_key, api_secret) #setting up client with keys

In [9]:
pd.DataFrame(client.get_historical_klines('BTCUSDT', '1m', '30 min ago UTC') )
#gets bitcoin data from 30 minutes ago in 1 minute intervals

,0,1,2,3,4,5,6,7,8,9,10,11
0,1661968980000,19982.37000000,19984.68000000,19961.22000000,19966.19000000,152.18667000,1661969039999,3039361.57751800,3900,76.89749000,1535773.09743670,0
1,1661969040000,19964.73000000,19995.23000000,19964.31000000,19992.31000000,141.50620000,1661969099999,2827566.43941470,3453,72.52639000,1449264.31186460,0
2,1661969100000,19991.47000000,20001.22000000,19978.30000000,19989.75000000,174.09820000,1661969159999,3480358.12500990,3351,100.35240000,2006140.28857170,0
3,1661969160000,19989.75000000,19995.91000000,19973.00000000,19974.70000000,220.27620000,1661969219999,4402153.22359220,3476,113.47382000,2267807.24482110,0
4,1661969220000,19974.70000000,20017.38000000,19973.00000000,20011.22000000,249.99132000,1661969279999,4998016.78061460,4987,131.09796000,2621169.16105820,0
5,1661969280000,20011.18000000,20047.58000000,20002.32000000,20028.08000000,316.39796000,1661969339999,6335954.76298330,6000,150.49680000,3013788.28642700,0
6,1661969340000,20026.59000000,20045.86000000,20021.59000000,20037.18000000,189.31084000,1661969399999,3792231.24230990,3943,108.19758000,2167477.90603570,0
7,1661969400000,20037.18000000,20044.97000000,20017.14000000,20028.71000000,179.23209000,1661969459999,3589797.93769590,3972,79.42289000,1590787.22875690,0
8,1661969460000,20027.60000000,20028.74000000,20000.05000000,20012.41000000,198.94837000,1661969519999,3981681.73509120,3779,70.67162000,1414380.61696220,0
9,1661969520000,20010.62000000,20025.25000000,20009.23000000,20021.07000000,134.84187000,1661969579999,2699250.07529050,2960,71.42896000,1429898.72874130,0
10,1661969580000,20020.18000000,20022.00000000,20005.13000000,20009.31000000,151.21397000,1661969639999,3026363.69276530,2861,70.50093000,1411071.05150480,0
11,1661969640000,20009.31000000,20021.78000000,20004.41000000,20015.85000000,104.05182000,1661969699999,2082421.88567390,2199,54.48532000,1090451.87282740,0
12,1661969700000,20015.85000000,20035.46000000,20014.66000000,20028.81000000,181.85444000,1661969759999,3641676.08055510,3401,105.65770000,2115910.01718820,0
13,1661969760000,20030.34000000,20031.32000000,20004.94000000,20005.07000000,177.87796000,1661969819999,3560525.02745120,3099,71.69683000,1435106.09302380,0
14,1661969820000,20005.07000000,20014.06000000,19995.06000000,20002.66000000,217.89595000,1661969879999,4358665.29881970,3930,113.80280000,2276567.26674230,0
15,1661969880000,20002.66000000,20013.88000000,19999.81000000,20011.31000000,174.78318000,1661969939999,3496721.29122460,3359,116.92389000,2339235.87512190,0
16,1661969940000,20013.28000000,20014.12000000,19994.34000000,19997.87000000,193.21425000,1661969999999,3864821.55736520,4285,109.42199000,2188807.24853510,0
17,1661970000000,19999.12000000,20004.26000000,19983.04000000,19984.10000000,202.10098000,1661970059999,4041198.98757850,4243,106.43108000,2128342.32971030,0
18,1661970060000,19985.27000000,19998.39000000,19979.82000000,19986.56000000,138.35246000,1661970119999,2765454.08368140,3340,70.06126000,1400455.64176150,0
19,1661970120000,19987.09000000,20015.74000000,19984.70000000,20014.05000000,170.89064000,1661970179999,3418326.91975780,3236,103.15940000,2063548.51357040,0
20,1661970180000,20012.38000000,20025.92000000,20004.34000000,20006.55000000,168.30732000,1661970239999,3368658.81356450,3323,82.28365000,1647032.40763650,0
21,1661970240000,20006.55000000,20013.15000000,19997.50000000,19999.94000000,119.02483000,1661970299999,2381015.07919750,2686,64.60698000,1292435.37208550,0
22,1661970300000,20001.16000000,20024.40000000,19999.82000000,20023.81000000,176.16434000,1661970359999,3526032.98400300,3201,93.42354000,1869945.91069420,0
23,1661970360000,20022.76000000,20023.81000000,20004.00000000,20006.16000000,171.85872000,1661970419999,3439346.75626190,3234,82.17880000,1644666.11501120,0
24,1661970420000,20006.16000000,20032.37000000,20002.67000000,20031.07000000,191.05834000,1661970479999,3824715.34203600,3158,103.06310000,2063265.28827720,0
25,1661970480000,20031.07000000,20040.00000000,20028.28000000,20034.06000000,160.46516000,1661970539999,3214885.03647930,3358,71.62784000,1435106.87265070,0
26,1661970540000,20032.83000000,20042.07000000,20015.77000000,20017.65000000,181.57701000,1661970599999,3636767.14878470,3319,95.58551000,1914599.54570880,0
27,1661970600000,20017.65000000,20017.70000000,19998.37000000,19999.88000000,171.23341000,1661970659999,3425862.71526000,3152,70.48923000,1410365.63549810,0
28,1661970660000,19999.88000000,19999.90000000,19981.22000000,19986.39000000,128.32320000,1661970719999,2565124.02997630,3401,61.78802000,1235109.43067100,0
29,1661970720000,19986.39000000,19994.28000000,19978.00000000,19980.77000000,135.95997000,1661970779999,2717245.74215060,2884,54.91194000,1097488.04260700,0

In [16]:
def cleanData(coin, interval, lookback): #function to clean the data and return clean datafram of wanted information
    frame = pd.DataFrame(client.get_historical_klines(coin, interval, lookback + ' min ago UTC')) #creates dataframe
    frame = frame.iloc[:, :6] #we only need first 6 columns of data for this project
    frame.columns = ['Time', 'Open', 'High', 'Low', 'Close', 'Volume'] #these are given in the website information
    frame = frame.set_index('Time') #time is set as index
    frame.index = pd.to_datetime(frame.index, unit = 'ms') #time is by default in unix, so we convert to easier time
    frame = frame.astype(float)
    return frame

In [19]:
test = cleanData('DOGEUSDT', '1m', '30')

In [21]:
#buy is asset fell by more than 0.3% within last 30 min
#sell if asset rises by more than 0.2% or falls further than 0.15% within last 30 min
def basicStrat(coin, quantity, bought = False):
    df = cleanData(coin, '1m', '30m') #creates dataframe
    cumulReturn = (df.Open.pct_change() + 1).cumprod() - 1 #calculates cumulative return
    if not bought:
        if cumulReturn[-1] < -0.003: #if coin drops by 0.3%, then buy
            order = client.create_order(coin = coin, side = 'BUY', type = 'MARKET', quantity = quantity)
            print(order)
            bought = True
        else:
            print('No Trade Executed')
    if bought:
        while True:
            df = cleanData(coin, '1m', '30m') #updates dataframe
            sinceBuy = df.loc[df.index > pd.to_datetime(order['transactionTime'], unit = 'ms')] #checks time since purchase
            if len(sinceBuy) > 0:
                sinceBuyRet = (sinceBuy.Open.pct_change() + 1).cumprod() - 1 #calculates cumulative return
                if sinceBuyRet[-1] > 0.002 or sinceBuyRet[-1] < -0.0015: #if one of the two are fulfilled then sell
                    order = client.create_order(coin = coin, side = 'SELL', type = 'MARKET', quantity = quantity)
                    print(order)
                    break

In [22]:
basicStrat('DOGEUSDT', 0.001)

No Trade Executed